### ISSUE TITLE
Zombie.js on Openshift

### ISSUE THREAD

**Issue by reyy** [ajay-gandhi/autopoke#2]
Hey, I noticed that you previously used Zombie.js before changing it to request promise and cheerio. Just wanted to check if you ever got Zombie.js to work on openshift?

I'm stuck with getting a callback before the page is fully loaded, resulting in the following error:

> TypeError: Cannot use 'in' operator to search for 'compareDocumentPosition' in null

Thanks!

**Comment by ajay-gandhi** [comment]
I had the same error while working with Zombie.js and Openshift, but I never found a solution.

I really recommend using request and cheerio, it's very simple and lightweight.
